export const AppConstants = {
  fcmProviderId: '',
  apnsProviderId: '',
  authKey: '',
  appId: '16821203e71872c8c',
  region: 'IN',
  subscriptionType: 'ALL_USERS',
  versionNumber: 'V5.2.2',
  webClientId: '',
  iosClientId: '',
  apiBaseUrl: process.env.EXPO_PUBLIC_API_BASE_URL || 'http://localhost:3000',
};

export const SCREEN_CONSTANTS = {
  SIGN_IN: 'SignIn',
  SIGN_UP: 'SignUp',
  BOTTOM_TAB_NAVIGATOR: 'BottomTabNavigator',
  CHATS: 'Chats',
  CALLS: 'Calls',
  USERS: 'Users',
  GROUPS: 'Groups',
  CONVERSATION: 'Conversation',
  MESSAGES: 'Messages',
  USER_INFO: 'UserInfo',
  GROUP_INFO: 'GroupInfo',
  ADD_MEMBER: 'AddMember',
  TRANSFER_OWNERSHIP: 'TransferOwnership',
  BANNED_MEMBER: 'BannedMember',
  VIEW_MEMBER: 'ViewMembers',
  CALL_LOGS: 'CallLogs',
  CALL_DETAILS: 'CallDetails',
  CALL_SCREEN: 'CallScreen',
  INCOMING_CALL: 'IncomingCall',
  SETTINGS_LIST: 'SettingsList',
  ACCOUNT_SETTINGS: 'AccountSettings',
  THEME_SETTINGS: 'ThemeSettings',
} as const;
